# Modalities and channels of delivery {-}

Between 2018 and 2020, most of Germany’s ODA to data and statistics was provided in the form of project-type interventions (83%) and pooled funding and contributions to specific programmes of implementing partners (14%) (Figure 6). 

Between 2018 and 2020, Germany's support was channelled through public-sector entities in Germany and in partner countries (63%), research and teaching institutions (15%) and multilateral organisations (i.e. multi-bi; 19%), with key partners including the IMF, the FAO and the World Bank (Figure 7). There is an interesting trend in that support at the beginning of the decade was mainly channelled through public-sector entities, while multilateral organisations were the dominant channel in 2014-16. Support to research and teaching institutions increased thereafter. An important partner in this last category is the [Center for International Forestry Research](https://www.cifor.org/), a non-profit organisation that conducts scientific research on the use and management of forests.

